# Generated by Django 4.2.3 on 2023-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options_alter_user_username_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={
                    "unique": "Пользователь с таким e-mail уже существует."
                },
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
