# Generated by Django 4.2.3 on 2023-07-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_auth",
        ),
    ]
