# Generated by Django 4.2.3 on 2023-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_unique_auth"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email", "username"), name="unique_auth"
            ),
        ),
    ]
